name: Deploy Next Js App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: install dependency
        run: npm install
      - name: Build Next Js App
        run: npm run build
      - name: deploy app
        run: echo "Deployig app...."
      
