name: next js build with caching and artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v5.0.0

       - name: Setup Node.js environment
         uses: actions/setup-node@v6.0.0
         with:
           node-version: 22.x
           cache: 'npm'

       - name: install dependecy
         run: npm install

       - name: next js build
         run: npm run build

       - name: Upload a Build Artifact
         uses: actions/upload-artifact@v5.0.0
         with:
           name: next-js-build
           path: out/

         

         
      
