name: depoy nextjs app

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: build
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: install dependency
        run: npm install
      - name: build next js
        run: npm run build
      - name: deploy
        run: echo "deploying...."
      
